### ISSUE TITLE
Export option

### ISSUE THREAD

**Issue by eyalev** [autokey-py3/autokey-py3#11]
Hi,

Is there an export option to backup all the AutoKey configs?

P.S
Amazing project, great work, and thanks :)

**Comment by troxor** [comment]
No explicit "export" that I know of, except for copying ~/.config/autokey somewhere else.

**Comment by eyalev** [comment]
Do you know where the `Window Filter` settings are being saved? I've looked in ~/.config/autokey but haven't found them.

**Comment by troxor** [comment]
Where do you see those settings? Every configuration option is stored in `lib/autokey/common.py:CONFIG_DIR = os.path.join(os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config')), "autokey")`, which should be `~/.config/autokey`
