### ISSUE TITLE
clipboard.fill_selection() fails and causes autokey gui to hang

### ISSUE THREAD

**Issue by xaaron** [autokey-py3/autokey-py3#18]
I am on Arch x64.  I execute the following script with ;;uc and it clears my trigger and functions as expected outputting the selection in uppercase:

cb = clipboard.get_selection()
# clipboard.fill_selection(cb.upper())

keyboard.send_keys(cb.upper())

The following code causes autokey GUI to freeze and does not provide any output to the keyboard:
cb = clipboard.get_selection()
clipboard.fill_selection(cb.upper())
keyboard.send_keys(cb.upper())

Also note that autokey is still running in the background and will work normally on non clipboard related scripts absent the ability to access the gui.

I've been able to resolve the issue by following the solution provided here:  
https://code.google.com/archive/p/autokey/issues/212

My specific change was:
1.  edit /usr/lib/python3.5/site-packages/autokey/scripting.py
2.  change GtkClipboard:__fillSelection(): self.selection.set_text(string) to: self.selection.set_text(string, -1)
3  restart autokey

**Comment by andresmrm** [comment]
Had the same problem.

    TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)

Thanks for pointing to a solution, @xaaron . =)
