### ISSUE TITLE
Issue pasting into QT5 apps via Keyboard

### ISSUE THREAD

**Issue by rparkhunovsky** [autokey-py3/autokey-py3#25]
Neither original 0.90.4 nor latest autokey-py3 git copes with pasting phrases and executing scripts in Qt5 application like Kate, Konsole or KDE Plasma 5.6 authorization dialog box using Keyboard method via a hotkey. Meanwhile it works well in any other application except of Qt5 based.
When you push the hotkey it either prints nothing or some garbage symbols (which are not even in the phrase) or does something unpredictable at all (like closes tabs).
I've tried -l option but didn't see anything explanatory to find out the problem.

---

KDE Plasma 5.6.3
Kate and Konsole version 16.04.0
KDE Frameworks 5.21.0
Qt 5.6.0 (built against 5.6.0)

**Comment by fodiator** [comment]
I suspect this is related to bug #20 which had been issued here by me. Unfortunately it seems like this project is actually quite abandoned as there are no reactions from the developers.

**Comment by troxor** [comment]
Can you retry this with latest git `HEAD` and reopen with a repeatable test case if it reoccurs and is distinct from #20 ?
