### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by txhammer68** [autokey-py3/autokey-py3#26]
Just installed and getting this error:
ammer@DigiServer:~$ autokey-qt -l
  File "/usr/local/bin/autokey-qt", line 33
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/autokey-qt on line 33, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
hammer@DigiServer:~$ autokey-gtk -l
  File "/usr/local/bin/autokey-gtk", line 26
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/autokey-gtk on line 26, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by Ianwu0812** [comment]
I have same problem too.

I have tried fix it by myself with adding 
># encoding=utf8

it still does't work

**Comment by troxor** [comment]
This should be fixed in the latest code, please reopen if it isn't.
