### ISSUE TITLE
error when try to open

### ISSUE THREAD

**Issue by el3ctron** [autokey-py3/autokey-py3#28]
i have a Linux Mint 17.1 Rebecca, and after installation steps i try to open autokey and console says:

installed with “pip install -e”
Traceback (most recent call last):
  File "/home/el3ctron/.local/bin/autokey-gtk", line 28, in <module>
    from autokey.gtkapp import Application
ImportError: No module named 'autokey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/el3ctron/.local/bin/autokey-gtk", line 31, in <module>
    from src.lib.gtkapp import Application
ImportError: No module named 'src'

**Comment by snaumov** [comment]
same error

**Comment by Henni** [comment]
Seems like 1f5642ef4139066c1661c4856baacfb1435c256d uses the module `typing` which is just available since Python 3.5 (https://docs.python.org/3/library/typing.html).

**Comment by troxor** [comment]
Can you try again with latest version in git?
