### ISSUE TITLE
AutoKey - Collaboration ...

### ISSUE THREAD

**Issue by josephj11** [autokey-py3/autokey-py3#3]
Hi. I'm an active AutoKey user (original version). I just found your project. It's good to see someone advancing AutoKey.

Would any of your code be useful to the original AutoKey?

Chris Deckter (one of the original developers) left the project a couple of years ago.

We currently have a volunteer developer, Jordan Metzmeier, who has fixed some bugs (for which we are very grateful!), but isn't otherwise very active. His code is at the address below. You may find some fixes you can use with your version.

https://github.com/jmetzmeier/autokey

Would you have any interest in getting involved?

It's my impression that a lot of people have yet to move to Python 3, so there still is a need for the Python 2.7 version.

Thanks.

Joe

**Comment by ReneSac** [comment]
The page you link to was erased. Is it now: https://github.com/autokey/autokey ?

Also, google code will cease it's services and erase everything soon. We need a alternative home for the documentation that is hosted there.

**Comment by josephj11** [comment]
Sorry for getting back to you so late. I don't check my gmail account very
often. Yes, that new link is correct. It's sort of alpha code at the moment
because our developer is busy on other projects, but since it's mainly bug
fixes, it should be OK.

I'm thinking of moving all the docs to github, but since I know almost
nothing about git, I haven't tried it yet. I have access to
autokey/autokey, but I don't want to to gum it up by importing things
incorrectly. I may try to set up my own project and import it there first,
so if anything goes wrong, it won't affect anyone except me.

**Comment by troxor** [comment]
Hi guys, if you were still interested in helping, I'd be happy to invite you to collaborate here. Just let guoci or me know.
