### ISSUE TITLE
IBus ... why not?

### ISSUE THREAD

**Issue by guettli** [autokey-py3/autokey-py3#31]
AFAIK up to now you don't use ibus.

Are there reasons why you don't use it?

**Comment by troxor** [comment]
That would be a question for the original author(s). It looks like a non-trivial amount of effort to implement; patches are welcome, though!

**Comment by guettli** [comment]
@troxor have you looked at the API of IBus?

Would you use it, if you would start from scratch?

I have a related project and I am unsure which library to choose. It would be nice to get a hint from someone who has more knowledge in this area than I have :-)

**Comment by troxor** [comment]
@guettli only enough to get an idea of what it does, since I have no need for it myself yet. It looks nice, but again, I have never used it.
