### ISSUE TITLE
2 things -  1. could not install this 2. Can we have a custom folder to store scripts?

### ISSUE THREAD

**Issue by phd21** [autokey-py3/autokey-py3#34]
Dear guoci,

I really love and depend upon this great application Autokey, but I do not see where it is being maintained any more. I guess this is your fork of that? If it is thank you for continuing this extremely useful program.

Two things
I. I could not install this using the instructions on my Linux Mint 17.3 KDE (32-bit) (autokey-qt). I already have the original autokey installed. This created a new menu entry, but it will not start. Luckily, the original still works. It looks like you are using the same name, will that create a conflict? Why not name it "autokey2-qt" or "AutoKey2016-qt", or something like that?

It would also certainly be great to have an easy to install ".deb" file for 32-bit and 64-bit, or a PPA, please.

II. Can we have a custom default folder to store and use scripts and phrases that is user defined? It would make backing up the installed scripts much easier then under the hidden folder "/home/user/.config/autokey". I would like to use my "Documents" folder and a sub-folder like "Autokey".

Thank you for your consideration.

**Comment by troxor** [comment]
1. Try reinstalling from latest git. There are still a couple bugs, but it runs for me at this point.
2. Patches welcome! `ln -s $HOME/.config/autokey $HOME/Documents/Autokey` in the meantime.
