### ISSUE TITLE
Gtk import error

### ISSUE THREAD

**Issue by sdothum** [autokey-py3/autokey-py3#37]
Arch install issues this message launching autokey-gtk:

/usr/lib/python3.5/site-packages/autokey/gtkapp.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

**Comment by malcolmocean** [comment]
I'm getting the same issue too, on Ubuntu 16.04.

**Comment by malcolmocean** [comment]
Here's something from a year ago about a similar issue with apport: https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1502173

Seems the solution might be just changing a few lines in the source...

**Comment by troxor** [comment]
Added the required lines where needed. Please test and see what (if anything) I broke!
