### ISSUE TITLE
Forked at autokey-py3/autokey-py3

### ISSUE THREAD

**Issue by troxor** [autokey-py3/autokey-py3#38]
I forked the repository at github.com/autokey-py3/autokey-py3 to try and solve some longstanding issues. Anyone who wants to help is welcome.

**Comment by guoci** [comment]
I suggest that I transfer ownership of my repo to the autokey-py3 organization instead, since all the stars and watchers are here.
What do you think?

**Comment by troxor** [comment]
Cool, that sounds good... the migrated issues didn't look as good anyway.

**Comment by guoci** [comment]
or we can consider to continue development here so no links will break.
Anyway, I can't transfer ownership for now as I have no admin rights to the organization.

**Comment by troxor** [comment]
Granted admin rights + sent another invite. I'll delete the existing autokey-py3 repository in that organization.

**Comment by troxor** [comment]
Looks good, thanks!
