### ISSUE TITLE
Will not install on Linux Mint 17.1 KDE

### ISSUE THREAD

**Issue by winterlaite** [autokey-py3/autokey-py3#7]
The setup.py file has errors. At line 24, it references a non-existent file. I changed the name of README to README.rst and it installed, but nothing it built runs. I could not build a .deb because of missing file errors. I know this is a good program, but I find it difficult to believe anyone could install it on a *buntu 14.04 distribution in its present state. (By the way, 0.90* throws dbus-related errors, so it's not like there's even a working version for Mint 17.1 anywhere that I can tell.)

**Comment by guoci** [comment]
setup.py does not refer to 'README' at all. How did you install it? The installation instructions are in README.rst.

**Comment by winterlaite** [comment]
On Thursday, March 05, 2015 05:13:30 PM guoci wrote:
> setup.py does not refer to 'README' at all. How did you install it? The
> installation instructions are in README.rst.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guoci/autokey-py3/issues/7#issuecomment-77488091
The .tgz is the latest.
Here is the directory listing.
total 56
drwxr-xr-x 5 winter winter 4096 Mar  6 08:36 .
drwxr-xr-x 4 winter winter 4096 Mar  6 08:33 ..
-rw-r--r-- 1 winter winter    0 Mar  6 08:36 autokeydirectory.txt
-rw-r--r-- 1 winter winter 1182 Feb 20  2014 autokey-gtk
-rw-r--r-- 1 winter winter 2044 Feb 20  2014 autokey-qt
-rw-r--r-- 1 winter winter 1876 Feb 20  2014 autokey-run
-rwxr-xr-x 1 winter winter  933 Feb 20  2014 autokey-shell
drwxr-xr-x 5 winter winter 4096 Feb 16 19:06 config
drwxr-xr-x 3 winter winter 4096 Feb 16 19:06 doc
-rw-r--r-- 1 winter winter  390 Jan 28  2014 INSTALL
-rw-r--r-- 1 winter winter 6063 Feb 16 19:06 PKG-INFO
-rw-r--r-- 1 winter winter  439 Jan 28  2014 README
-rw-r--r-- 1 winter winter 3169 Feb 16 18:42 setup.py
drwxr-xr-x 3 winter winter 4096 Feb 16 19:06 src

As you can see, there is no README.rst.

Here's the excerpt from setup.py:

from distutils.core import setup

long_description = ''
try:
    with open('README.rst') as f:
        long_description = f.read()
except FileNotFoundError: pass

There is no README.rst provided. That's why I renamed README, as I stated.

The installed files did not run.
This may be relevant:
https://bugzilla.redhat.com/show_bug.cgi?id=1153809

Thank you.

**Comment by guoci** [comment]
It seems that you are using python 2, this is a python 3 only application. Use pip3 instead of pip. Please see README.rst for more information.

**Comment by winterlaite** [comment]
Thanks for the quick response. Actually I had installed it from the master.zip files using the setup.py script with "python setup.py install" according to the instructions. (I did this after following the pip3 instructions to the letter, which didn't work).

Should I have used "python3 setup.py install"?
Thanks again for your help.

**Comment by guoci** [comment]
The install instructions are at https://github.com/guoci/autokey-py3. Scroll down to read README.rst.

**Comment by winterlaite** [comment]
Actually, my reading the instructions is what led me here. Yesterday I followed all the Debian instructions for pip3 install to the letter. When those failed, I attempted to install from the source files.
Thanks.

**Comment by guoci** [comment]
ok. Can you paste all output of "pip3 install --user autokey-py3"? And your Python 3 version " python3 --version"?

**Comment by winterlaite** [comment]
On Friday, March 06, 2015 05:36:12 PM guoci wrote:
> ok. Can you paste all output of "pip3 install --user autokey-py3"? And your
> Python 3 version " python3 --version"?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guoci/autokey-py3/issues/7#issuecomment-77665931
Thanks again for the quick response. It'll be tomorrow before I can try to 
reinstall.
python3 --version: Python 3.4.0
I appreciate your help.

**Comment by winterlaite** [comment]
Traceback (most recent call last):
  File "/home/winter/.local/bin/autokey-gtk", line 28, in <module>
    from autokey.gtkapp import Application
Followed directions and rant autokey-gtk.

ImportError: No module named 'autokey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/winter/.local/bin/autokey-gtk", line 31, in <module>
    from src.lib.gtkapp import Application
ImportError: No module named 'src'

**Comment by guoci** [comment]
I believe you did not install it correctly. Can you do the following?
```bash
sudo apt-get install python3-pyinotify wmctrl xautomation imagemagick  python3-pykde4 python3-pyqt4.qsci python3-dbus.mainloop.qt kde-baseapps-bin python3-pip
pip3 install --user python3-xlib
pip3 install --user autokey-py3
$HOME/.local/bin/autokey-qt
```

**Comment by troxor** [comment]
Please try removing any existing installation and reinstalling from git.
